export const profileData = {
  name: "Aditya Tri Ananta",
  title: "Electrical Engineer",
  subtitle: "Engineering Portfolio",
  intro: "Designing the future of aerospace, one precision component at a time. From SpaceX Starship to Google Pixel — I bring engineering rigor to every project.",
  linkedin: "https://www.linkedin.com/in/aditya-tri-ananta/",
  email: "adityatriananta@gmail.com",
};

export const experiences = [
  {
    id: "PLNIP",
    company: "PLN Indonesia Power",
    role: "Electricity HAR",
    date: "Sep 2025 - Nov 2025",
    location: "Banjarnegara, Indonesia",
    description: "Supported commissioning and recommissioning through wiring verification and functional testing",
    logo: "PLNIP",
    color: "#4285F4",
  },
  {
    id: "S2P",
    company: "Sumber Segara Primadaya",
    role: "Maintenance Building Electrical Unit 1&2",
    date: "Jan 2025 - Feb 2025",
    location: "Cilcap, Indonesia",
    description: "Maintained operational reliability of ESP and high-voltage systems",
    logo: "S2P",
    color: "#A2AAAD",
  },
  {
    id: "PLN",
    company: "PLN (Persero)",
    role: "JarGI Operations Assistant",
    date: "Jul 2024 - Aug 2024",
    location: "Cilcap, Indonesia",
    description: "Conducted in-service inspection and measurement tests (IL1 & IL2)",
    logo: "PLN",
    color: "#005288",
  },
  {
    id: "CV",
    company: "CV Multiservice",
    role: "Assistant Technician",
    date: "Oct 2021 - Dec 2021",
    location: "Cilcap, Indonesia",
    description: "Troubleshooting and repair of electrical appliances and systems",
    logo: "CV",
    color: "#0033A0",
  },
];

// ===== 20 UNIQUE PROJECTS =====
export const projects = [
  // ===== PROFESSIONAL (6 projects) =====
  {
    id: "pixel-design",
    title: "Google Pixel Design",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Professional",
    domain: "PRODUCT_DESIGN",
    shortDesc: "Pixel phone mechanical design engineering at Google.",
    fullDesc: "Led mechanical design initiatives for Google Pixel smartphone lineup. Managed complex tolerancing challenges across multi-material assemblies, coordinated with cross-functional teams on thermal management solutions, and drove DFM improvements resulting in significant yield improvements across production lines.",
    technologies: ["PVsyst", "Creo", "QGIS", "FEA"],
    year: "2023",
  },
  {
    id: "thermal-management-system",
    title: "Advanced Thermal Management System",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Professional",
    domain: "THERMAL_ENGINEERING",
    shortDesc: "Innovative cooling solution for high-performance processors.",
    fullDesc: "Designed and implemented an advanced thermal management system for next-generation processors. Conducted CFD simulations, optimized heat sink geometry, selected premium thermal interface materials, and validated performance through extensive testing. Achieved 40% improvement in thermal conductivity.",
    technologies: ["Arduino Ide", "CFD", "SolidWorks", "Thermal Analysis"],
    year: "2023",
  },
  {
    id: "precision-machining",
    title: "Precision Machining Operations",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Professional",
    domain: "MANUFACTURING",
    shortDesc: "Streamlined CNC machining processes for aerospace components.",
    fullDesc: "Optimized CNC machining workflows for precision aerospace components. Implemented tool path optimization, reduced cycle times by 35%, improved surface finish accuracy to ±0.005 inches, and developed comprehensive tooling documentation for production teams.",
    technologies: ["SolidWorks", "CAM Software", "CNC", "QGIS"],
    year: "2023",
  },
  {
    id: "vibration-analysis",
    title: "Vibration & Dynamic Analysis",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Professional",
    domain: "STRUCTURAL_ANALYSIS",
    shortDesc: "Modal analysis and vibration control for satellite structures.",
    fullDesc: "Performed comprehensive modal and vibration analysis on satellite structural components. Used FEA to predict natural frequencies, implemented vibration damping strategies, and validated designs through environmental testing. Successfully controlled resonance frequencies.",
    technologies: ["Arduino Ide", "FEA", "ETAP", "Vibration Testing"],
    year: "2023",
  },
  {
    id: "supply-chain-optimization",
    title: "Supply Chain Optimization",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Professional",
    domain: "PROCESS_IMPROVEMENT",
    shortDesc: "Logistics and procurement process optimization.",
    fullDesc: "Led supply chain optimization initiative reducing lead times by 25%. Implemented vendor qualification system, created supplier scorecards, optimized part sourcing strategy, and established just-in-time delivery protocols. Resulted in $2.5M annual cost savings.",
    technologies: ["Excel", "Power BI", "SAP", "Data Analysis"],
    year: "2022",
  },
  {
    id: "material-selection-analysis",
    title: "Material Selection & Analysis",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Professional",
    domain: "MATERIALS_ENGINEERING",
    shortDesc: "Comprehensive material evaluation for high-performance applications.",
    fullDesc: "Conducted extensive material selection study for aerospace and automotive applications. Evaluated properties including strength-to-weight ratio, thermal resistance, cost, and manufacturability. Selected optimal materials for 15+ designs, resulted in 20% weight reduction.",
    technologies: ["MatWeb", "ETAP", "Testing Standards", "CES Software"],
    year: "2022",
  },

  // ===== INTERNSHIP (6 projects) =====
  {
    id: "iphone-14",
    title: "iPhone 14 Development",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Internship",
    domain: "CONSUMER_ELECTRONICS",
    shortDesc: "Mechanical design & development of iPhone 14 lineup at Apple.",
    fullDesc: "Contributed to the mechanical design and development of the iPhone 14 lineup at Apple. Worked on internal structural components, managed prototype builds, conducted tolerance analyses for precision assemblies, and collaborated with manufacturing teams.",
    technologies: ["NX", "CATIA", "Tolerance Analysis", "Prototyping"],
    year: "2022",
  },
  {
    id: "starship",
    title: "SpaceX Starship",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Internship",
    domain: "AEROSPACE_STRUCTURES",
    shortDesc: "Starship nosecone build process & internal structures design.",
    fullDesc: "Responsible for the build process of Starship nosecone and driving internal structures design at SpaceX Brownsville facility. Developed assembly procedures for nosecone tile attachment, designed internal structural brackets, and created fixtures for precision alignment.",
    technologies: ["SolidWorks", "QGIS", "Welding Fixtures", "Sheet Metal"],
    year: "2021",
  },
  {
    id: "new-glenn",
    title: "Blue Origin New Glenn",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Internship",
    domain: "AEROSPACE_ENGINEERING",
    shortDesc: "Large launch vehicle structural analysis and design.",
    fullDesc: "Performed structural analysis on New Glenn booster and upper stage primary structures. Conducted FEA studies for launch and flight loads, optimized structural layouts for minimum weight while meeting stress constraints, and created detailed design documentation.",
    technologies: ["ABAQUS", "Catia", "Stress Analysis", "Documentation"],
    year: "2021",
  },
  {
    id: "boeing-787",
    title: "Boeing 787 Dreamliner",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Internship",
    domain: "COMMERCIAL_AIRCRAFT",
    shortDesc: "Composite fuselage panel manufacturing and testing.",
    fullDesc: "Worked on composite fuselage panel manufacturing processes for Boeing 787. Developed quality control procedures, conducted impact testing and non-destructive evaluation, optimized manufacturing parameters, and contributed to cost reduction initiatives.",
    technologies: ["Composites", "CATIA", "Testing", "Quality Control"],
    year: "2020",
  },
  {
    id: "gm-vehicle",
    title: "General Motors Vehicle Design",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Internship",
    domain: "AUTOMOTIVE",
    shortDesc: "Suspension system design and NVH analysis.",
    fullDesc: "Designed and analyzed suspension components for next-generation vehicle platform. Performed NVH (Noise, Vibration, Harshness) studies, optimized component geometry, conducted durability testing simulations, and created manufacturing drawings.",
    technologies: ["NX", "Adams", "Hypermesh", "CAM"],
    year: "2020",
  },

  // ===== STUDENT TEAM (4 projects) =====
  {
    id: "efficiency-challenge",
    title: "Shell Eco-Marathon Competition",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Student Team",
    domain: "EFFICIENT_VEHICLES",
    shortDesc: "Ultra-efficient vehicle design for fuel efficiency competition.",
    fullDesc: "Led mechanical design for Shell Eco-Marathon competition vehicle achieving 2,700 km/L equivalent efficiency. Optimized chassis for minimal drag, designed lightweight suspension, implemented advanced materials, and conducted extensive testing.",
    technologies: ["SolidWorks", "CFD", "Lightweight Design", "Testing"],
    year: "2022",
  },
  {
    id: "formula-student",
    title: "Formula Student Competition",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Student Team",
    domain: "FORMULA_RACING",
    shortDesc: "Formula SAE competition race car design and manufacturing.",
    fullDesc: "Designed and manufactured a complete Formula SAE race car from concept to competition. Engineered frame structure, suspension geometry, drivetrain integration, and aerodynamic components. Vehicle competed successfully in static and dynamic events.",
    technologies: ["SolidWorks", "FEA", "Manufacturing", "Suspension Design"],
    year: "2021",
  },
  {
    id: "robotics-challenge",
    title: "International Robotics Challenge",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Student Team",
    domain: "ROBOTICS",
    shortDesc: "Autonomous underwater vehicle for international competition.",
    fullDesc: "Engineered autonomous underwater vehicle for offshore exploration challenge. Designed pressure hull, thrusters, control systems, and sensor integration. Vehicle successfully completed depth testing to 1000m equivalent.",
    technologies: ["CAD", "Fluid Dynamics", "Electronics", "Control Systems"],
    year: "2021",
  },
  {
    id: "solar-car",
    title: "Solar Car Competition",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Student Team",
    domain: "RENEWABLE_ENERGY",
    shortDesc: "Lightweight chassis design for solar car competition.",
    fullDesc: "Engineered chassis and suspension system for solar-powered race car in international competition. Optimized frame for minimal weight while maintaining rigidity, integrated solar panel mounting points, designed suspension geometry. Vehicle completed 1000+ mile competition.",
    technologies: ["SolidWorks", "ETAP", "Suspension Design", "Composite Materials"],
    year: "2021",
  },

  // ===== PERSONAL (4 projects) =====
  {
    id: "injection-mold",
    title: "Plastic Injection Mold",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Personal",
    domain: "TOOLING_DESIGN",
    shortDesc: "Custom injection mold tool design and manufacturing.",
    fullDesc: "Designed and manufactured a complete plastic injection mold tool from A-plate to ejector plate. Created parting line analysis, designed cooling channels, specified steel selections for cavity and core, machined all components using CNC and EDM processes, and validated the mold.",
    technologies: ["SolidWorks", "CNC", "EDM", "MoldFlow"],
    year: "2021",
  },
  {
    id: "3d-printer-design",
    title: "Custom 3D Printer Design",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Personal",
    domain: "MECHANICAL_DESIGN",
    shortDesc: "Ground-up design and assembly of FDM 3D printer.",
    fullDesc: "Designed and built a fully functional FDM 3D printer from scratch incorporating best practices. Custom frame design using aluminum extrusions, designed hot end assembly, created heated bed system with PID control, and integrated Marlin firmware. Successfully prints parts with ±0.5mm accuracy.",
    technologies: ["SolidWorks", "CNC", "Electronics", "Firmware"],
    year: "2023",
  },
  {
    id: "cnc-mill-upgrade",
    title: "CNC Mill Hardware Upgrade",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Personal",
    domain: "MACHINE_TOOLS",
    shortDesc: "Precision upgrades to hobby CNC milling machine.",
    fullDesc: "Retrofitted hobby CNC mill with high-precision components and upgrades. Upgraded spindle bearings to sealed units, improved ballscrews with anti-backlash nuts, installed new limit switches and emergency stop system. Achieved ±0.01mm repeatability on small precision parts.",
    technologies: ["Mechanical Design", "Precision Measurement", "CAM", "Machining"],
    year: "2022",
  },
  {
    id: "microcontroller-project",
    title: "Embedded Systems Weather Station",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Personal",
    domain: "ELECTRONICS",
    shortDesc: "IoT weather monitoring system with multiple sensors.",
    fullDesc: "Developed comprehensive IoT weather station using Arduino/ESP32 microcontrollers. Integrated multiple sensors including temperature, humidity, barometric pressure, wind speed, and rainfall. Created cloud data logging system, built mobile-responsive web app for real-time monitoring. Accuracy within ±2% of commercial stations.",
    technologies: ["Arduino", "Proteus", "Cloud Services", "IoT"],
    year: "2022",
  },
  {
    id: "furniture-design",
    title: "Ergonomic Modular Desk System",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Personal",
    domain: "PRODUCT_DESIGN",
    shortDesc: "Custom designed multi-purpose workspace furniture.",
    fullDesc: "Designed and fabricated a modular workspace desk system optimized for ergonomics and functionality. Features include adjustable height for standing/sitting, integrated cable management channels, modular storage components, and aesthetic wood veneer finish. Used sustainable materials and precision CNC joinery.",
    technologies: ["SketchUp", "Woodworking", "Ergonomics", "Sustainable Design"],
    year: "2022",
  },
];

export const software = [
  { name: "PVsyst", proficiency: 95 },
  { name: "SolidWorks", proficiency: 98 },
  { name: "Cx-One", proficiency: 85 },
  { name: "Factory IO", proficiency: 80 },
  { name: "ETAP", proficiency: 90 },
  { name: "Proteus", proficiency: 85 },
  { name: "Arduino Ide", proficiency: 88 },
  { name: "AutoCAD", proficiency: 82 },
  { name: "HomerPro", proficiency: 75 },
  { name: "QGIS", proficiency: 95 },
  { name: "MoldFlow", proficiency: 70 },
  { name: "LabVIEW", proficiency: 72 },
];

// ===== EXPERIENCE IMAGES =====
export const experienceImages = {
  "PLNIP": "/foto/PLN Indonesia Power.png",
  "S2P": "/foto/S2P.png",
  "PLN": "/foto/PLN.png",
  "CV": "/foto/CV.png",
};

// ===== SOFTWARE WITH IMAGES =====
export const softwareWithImages = [
  {
    name: "PVsyst",
    image: "/foto/pvsyst.png",
    proficiency: 95,
  },
  {
    name: "Arduino Ide",
    image: "/foto/Arduino.png",
    proficiency: 88,
  },
  {
    name: "Cx-One",
    image: "/foto/PLC.png",
    proficiency: 85,
  },
  {
    name: "Factory IO",
    image: "/foto/Factory IO.png",
    proficiency: 80,
  },
  {
    name: "ETAP",
    image: "/foto/ETAP.png",
    proficiency: 90,
  },
  {
    name: "Proteus",
    image: "/foto/Proteus.png",
    proficiency: 85,
  },
  {
    name: "QGIS",
    image: "/foto/QGIS.png",
    proficiency: 95,
  },
  {
    name: "AutoCAD",
    image: "/foto/AutoCAD.png",
    proficiency: 82,
  },
  {
    name: "HomerPro",
    image: "/foto/HomerPro.png",
    proficiency: 75,
  },
  {
    name: "SolidWorks",
    image: "/foto/pngwing.com.png",
    proficiency: 98,
  },
  {
    name: "-",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Autodesk_Logo.svg/200px-Autodesk_Logo.svg.png",
    proficiency: 70,
  },
  {
    name: "-",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/National_Instruments_Logo.svg/200px-National_Instruments_Logo.svg.png",
    proficiency: 72,
  },
];

export const profileImage = "/foto/aku.png";