export const profileData = {
  name: "Aditya Tri Ananta",
  title: "Electrical Engineer",
  subtitle: "Engineering Portfolio",
  intro: "Designing the future of aerospace, one precision component at a time. From SpaceX Starship to Google Pixel — I bring engineering rigor to every project.",
  linkedin: "https://www.linkedin.com/in/aditya-tri-ananta/",
  email: "adityatriananta@gmail.com",
};

export const experiences = [
  {
    id: "PLNIP",
    company: "PLN Indonesia Power",
    role: "Electricity HAR",
    date: "Sep 2025 - Nov 2025",
    location: "Banjarnegara, Indonesia",
    description: "Supported commissioning and recommissioning through wiring verification and functional testing",
    logo: "PLNIP",
    color: "#4285F4",
  },
  {
    id: "S2P",
    company: "Sumber Segara Primadaya",
    role: "Maintenance Building Electrical Unit 1&2",
    date: "Jan 2025 - Feb 2025",
    location: "Cilcap, Indonesia",
    description: "Maintained operational reliability of ESP and high-voltage systems",
    logo: "S2P",
    color: "#A2AAAD",
  },
  {
    id: "PLN",
    company: "PLN (Persero)",
    role: "JarGI Operations Assistant",
    date: "Jul 2024 - Aug 2024",
    location: "Cilcap, Indonesia",
    description: "Conducted in-service inspection and measurement tests (IL1 & IL2)",
    logo: "PLN",
    color: "#005288",
  },
  {
    id: "CV",
    company: "CV Multiservice",
    role: "Assistant Technician",
    date: "Oct 2021 - Dec 2021",
    location: "Cilcap, Indonesia",
    description: "Troubleshooting and repair of electrical appliances and systems",
    logo: "CV",
    color: "#0033A0",
  },
];

// ===== 20 UNIQUE PROJECTS =====
export const projects = [
  // ===== PROFESSIONAL (6 projects) =====
  {
    id: "pixel-design",
    title: "Google Pixel Design",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Professional",
    domain: "PRODUCT_DESIGN",
    shortDesc: "Pixel phone mechanical design engineering at Google.",
    fullDesc: "Led mechanical design initiatives for Google Pixel smartphone lineup. Managed complex tolerancing challenges across multi-material assemblies, coordinated with cross-functional teams on thermal management solutions, and drove DFM improvements resulting in significant yield improvements across production lines.",
    technologies: ["PVsyst", "Creo", "QGIS", "FEA"],
    year: "2023",
  },
  {
    id: "thermal-management-system",
    title: "Advanced Thermal Management System",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Professional",
    domain: "THERMAL_ENGINEERING",
    shortDesc: "Innovative cooling solution for high-performance processors.",
    fullDesc: "Designed and implemented an advanced thermal management system for next-generation processors. Conducted CFD simulations, optimized heat sink geometry, selected premium thermal interface materials, and validated performance through extensive testing. Achieved 40% improvement in thermal conductivity.",
    technologies: ["Arduino Ide", "CFD", "SolidWorks", "Thermal Analysis"],
    year: "2023",
  },
  {
    id: "precision-machining",
    title: "Precision Machining Operations",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Professional",
    domain: "MANUFACTURING",
    shortDesc: "Streamlined CNC machining processes for aerospace components.",
    fullDesc: "Optimized CNC machining workflows for precision aerospace components. Implemented tool path optimization, reduced cycle times by 35%, improved surface finish accuracy to ±0.005 inches, and developed comprehensive tooling documentation for production teams.",
    technologies: ["SolidWorks", "CAM Software", "CNC", "QGIS"],
    year: "2023",
  },
  {
    id: "vibration-analysis",
    title: "Vibration & Dynamic Analysis",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Professional",
    domain: "STRUCTURAL_ANALYSIS",
    shortDesc: "Modal analysis and vibration control for satellite structures.",
    fullDesc: "Performed comprehensive modal and vibration analysis on satellite structural components. Used FEA to predict natural frequencies, implemented vibration damping strategies, and validated designs through environmental testing. Successfully controlled resonance frequencies.",
    technologies: ["Arduino Ide", "FEA", "ETAP", "Vibration Testing"],
    year: "2023",
  },
  {
    id: "supply-chain-optimization",
    title: "Supply Chain Optimization",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Professional",
    domain: "PROCESS_IMPROVEMENT",
    shortDesc: "Logistics and procurement process optimization.",
    fullDesc: "Led supply chain optimization initiative reducing lead times by 25%. Implemented vendor qualification system, created supplier scorecards, optimized part sourcing strategy, and established just-in-time delivery protocols. Resulted in $2.5M annual cost savings.",
    technologies: ["Excel", "Power BI", "SAP", "Data Analysis"],
    year: "2022",
  },
  {
    id: "material-selection-analysis",
    title: "Material Selection & Analysis",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Professional",
    domain: "MATERIALS_ENGINEERING",
    shortDesc: "Comprehensive material evaluation for high-performance applications.",
    fullDesc: "Conducted extensive material selection study for aerospace and automotive applications. Evaluated properties including strength-to-weight ratio, thermal resistance, cost, and manufacturability. Selected optimal materials for 15+ designs, resulted in 20% weight reduction.",
    technologies: ["MatWeb", "ETAP", "Testing Standards", "CES Software"],
    year: "2022",
  },

  // ===== INTERNSHIP (6 projects) =====
  {
    id: "iphone-14",
    title: "iPhone 14 Development",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Internship",
    domain: "CONSUMER_ELECTRONICS",
    shortDesc: "Mechanical design & development of iPhone 14 lineup at Apple.",
    fullDesc: "Contributed to the mechanical design and development of the iPhone 14 lineup at Apple. Worked on internal structural components, managed prototype builds, conducted tolerance analyses for precision assemblies, and collaborated with manufacturing teams.",
    technologies: ["NX", "CATIA", "Tolerance Analysis", "Prototyping"],
    year: "2022",
  },
  {
    id: "starship",
    title: "SpaceX Starship",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Internship",
    domain: "AEROSPACE_STRUCTURES",
    shortDesc: "Starship nosecone build process & internal structures design.",
    fullDesc: "Responsible for the build process of Starship nosecone and driving internal structures design at SpaceX Brownsville facility. Developed assembly procedures for nosecone tile attachment, designed internal structural brackets, and created fixtures for precision alignment.",
    technologies: ["SolidWorks", "QGIS", "Welding Fixtures", "Sheet Metal"],
    year: "2021",
  },
  {
    id: "new-glenn",
    title: "Blue Origin New Glenn",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Internship",
    domain: "COMPOSITE_MANUFACTURING",
    shortDesc: "New Glenn carbon fiber panels assembly optimization.",
    fullDesc: "Streamlined New Glenn carbon fiber panels assembly by conducting tolerance stack-up analyses and fixture design at Blue Origin. Designed and validated composite layup tooling, reduced assembly cycle time through improved process flows.",
    technologies: ["PVsyst", "Composites", "Tolerance Stacks", "Fixtures"],
    year: "2020",
  },
  {
    id: "battery-enclosure",
    title: "EV Battery Pack Enclosure Design",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Internship",
    domain: "AUTOMOTIVE_DESIGN",
    shortDesc: "Structural design and thermal analysis of EV battery housing.",
    fullDesc: "Designed robust battery pack enclosure for electric vehicle platform. Performed structural FEA under crash and impact loads, thermal analysis for heat dissipation, and environmental sealing design. Achieved IP67 rating and passed all automotive safety standards.",
    technologies: ["Creo", "Arduino Ide", "Thermal FEA", "QGIS"],
    year: "2022",
  },
  {
    id: "circuit-board-assembly",
    title: "PCB Assembly Process Development",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Internship",
    domain: "ELECTRONICS_MANUFACTURING",
    shortDesc: "SMT and wave soldering process optimization.",
    fullDesc: "Developed and optimized SMT and wave soldering processes for complex PCBs. Created reflow profiles, designed solder paste stencils, established quality control metrics, and trained manufacturing team. Improved first-pass yield from 94% to 98.5%.",
    technologies: ["Allegro PCB", "Manufacturing Procedures", "SPC", "Six Sigma"],
    year: "2022",
  },
  {
    id: "casting-simulation",
    title: "Metal Casting Simulation & Analysis",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Internship",
    domain: "FOUNDRY_ENGINEERING",
    shortDesc: "Advanced casting simulation for complex aluminum parts.",
    fullDesc: "Utilized casting simulation software to analyze metal flow, predict porosity, and optimize gating systems for aluminum cast components. Reduced scrap rate by 18%, improved dimensional accuracy, and shortened mold design cycle time.",
    technologies: ["ProCAST", "MAGMASOFT", "SolidWorks", "Metallurgy"],
    year: "2021",
  },

  // ===== STUDENT TEAM (4 projects) =====
  {
    id: "fsae-gearbox",
    title: "FSAE Planetary Gearbox",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Student Team",
    domain: "DRIVETRAIN_DESIGN",
    shortDesc: "Custom planetary gearbox for Formula SAE electric racecar.",
    fullDesc: "Designed and manufactured a custom planetary gearbox for the university Formula SAE electric racecar. Performed gear tooth stress analysis, selected bearings for high-speed operation, machined all housings and ring gears in-house, and validated performance. Achieved 97% efficiency.",
    technologies: ["SolidWorks", "ETAP", "CNC Machining", "FEA"],
    year: "2021",
  },
  {
    id: "hybrid-vehicle",
    title: "Hybrid Electric Powertrain System",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Student Team",
    domain: "AUTOMOTIVE_ENGINEERING",
    shortDesc: "Design and integration of hybrid powertrain for competition vehicle.",
    fullDesc: "Led powertrain integration team for hybrid electric vehicle in engineering competition. Designed and optimized power distribution system, integrated electric motor with traditional engine, created control algorithms, and managed battery management system. Vehicle achieved 45 MPGe.",
    technologies: ["SolidWorks", "ETAP/Simulink", "Battery Management", "Controls"],
    year: "2022",
  },
  {
    id: "drone-frame",
    title: "Carbon Fiber Drone Frame Design",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Student Team",
    domain: "AEROSPACE_COMPOSITE",
    shortDesc: "Lightweight composite structure for autonomous drone platform.",
    fullDesc: "Designed carbon fiber frame assembly for autonomous drone platform with high payload capacity. Performed composite FEA analysis, designed tooling for autoclave processing, manufactured and tested prototype. Achieved 40% weight reduction while maintaining structural integrity.",
    technologies: ["SolidWorks", "Composite FEA", "Autoclave Processing", "Test & Validation"],
    year: "2021",
  },
  {
    id: "solar-car",
    title: "Solar-Powered Vehicle Chassis",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Student Team",
    domain: "RENEWABLE_ENERGY",
    shortDesc: "Lightweight chassis design for solar car competition.",
    fullDesc: "Engineered chassis and suspension system for solar-powered race car in international competition. Optimized frame for minimal weight while maintaining rigidity, integrated solar panel mounting points, designed suspension geometry. Vehicle completed 1000+ mile competition.",
    technologies: ["SolidWorks", "ETAP", "Suspension Design", "Composite Materials"],
    year: "2021",
  },

  // ===== PERSONAL (4 projects) =====
  {
    id: "injection-mold",
    title: "Plastic Injection Mold",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Personal",
    domain: "TOOLING_DESIGN",
    shortDesc: "Custom injection mold tool design and manufacturing.",
    fullDesc: "Designed and manufactured a complete plastic injection mold tool from A-plate to ejector plate. Created parting line analysis, designed cooling channels, specified steel selections for cavity and core, machined all components using CNC and EDM processes, and validated the mold.",
    technologies: ["SolidWorks", "CNC", "EDM", "MoldFlow"],
    year: "2021",
  },
  {
    id: "3d-printer-design",
    title: "Custom 3D Printer Design",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Personal",
    domain: "MECHANICAL_DESIGN",
    shortDesc: "Ground-up design and assembly of FDM 3D printer.",
    fullDesc: "Designed and built a fully functional FDM 3D printer from scratch incorporating best practices. Custom frame design using aluminum extrusions, designed hot end assembly, created heated bed system with PID control, and integrated Marlin firmware. Successfully prints parts with ±0.5mm accuracy.",
    technologies: ["SolidWorks", "CNC", "Electronics", "Firmware"],
    year: "2023",
  },
  {
    id: "cnc-mill-upgrade",
    title: "CNC Mill Hardware Upgrade",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Personal",
    domain: "MACHINE_TOOLS",
    shortDesc: "Precision upgrades to hobby CNC milling machine.",
    fullDesc: "Retrofitted hobby CNC mill with high-precision components and upgrades. Upgraded spindle bearings to sealed units, improved ballscrews with anti-backlash nuts, installed new limit switches and emergency stop system. Achieved ±0.01mm repeatability on small precision parts.",
    technologies: ["Mechanical Design", "Precision Measurement", "CAM", "Machining"],
    year: "2022",
  },
  {
    id: "microcontroller-project",
    title: "Embedded Systems Weather Station",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Personal",
    domain: "ELECTRONICS",
    shortDesc: "IoT weather monitoring system with multiple sensors.",
    fullDesc: "Developed comprehensive IoT weather station using Arduino/ESP32 microcontrollers. Integrated multiple sensors including temperature, humidity, barometric pressure, wind speed, and rainfall. Created cloud data logging system, built mobile-responsive web app for real-time monitoring. Accuracy within ±2% of commercial stations.",
    technologies: ["Arduino", "Proteus", "Cloud Services", "IoT"],
    year: "2022",
  },
  {
    id: "furniture-design",
    title: "Ergonomic Modular Desk System",
    coverImage: "https://4kwallpapers.com/images/walls/thumbs_3t/26104.png",
    detailImage: "https://4kwallpapers.com/images/walls/thumbs_3t/25228.jpg",
    image: "https://media.base44.com/images/public/6a35597ab93951a70264ab70/28b92bf46_generated_0425762f.png",
    category: "Personal",
    domain: "PRODUCT_DESIGN",
    shortDesc: "Custom designed multi-purpose workspace furniture.",
    fullDesc: "Designed and fabricated a modular workspace desk system optimized for ergonomics and functionality. Features include adjustable height for standing/sitting, integrated cable management channels, modular storage components, and aesthetic wood veneer finish. Used sustainable materials and precision CNC joinery.",
    technologies: ["SketchUp", "Woodworking", "Ergonomics", "Sustainable Design"],
    year: "2022",
  },
];

export const software = [
  { name: "PVsyst", proficiency: 95 },
  { name: "SolidWorks", proficiency: 98 },
  { name: "Cx-One", proficiency: 85 },
  { name: "Factory IO", proficiency: 80 },
  { name: "ETAP", proficiency: 90 },
  { name: "Proteus", proficiency: 85 },
  { name: "Arduino Ide", proficiency: 88 },
  { name: "AutoCAD", proficiency: 82 },
  { name: "HomerPro", proficiency: 75 },
  { name: "QGIS", proficiency: 95 },
  { name: "MoldFlow", proficiency: 70 },
  { name: "LabVIEW", proficiency: 72 },
];


export const experienceImages = {
  "PLNIP": "foto/PLN Indonesia Power.png",
  "S2P": "foto/S2P.png",
  "PLN": "foto/PLN.png",
  "CV": "foto/CV.png",
};

// ===== SOFTWARE WITH IMAGES =====
export const softwareWithImages = [
  {
    name: "PVsyst",
    image: "foto/pvsyst.png",
    proficiency: 95,
  },
  {
    name: "Arduino Ide",
    image: "foto/Arduino.png",
    proficiency: 88,
  },
  {
    name: "Cx-One",
    image: "foto/PLC.png",
    proficiency: 85,
  },
  {
    name: "Factory IO",
    image: "foto/Factory IO.png",
    proficiency: 80,
  },
  {
    name: "ETAP",
    image: "foto/ETAP.png",
    proficiency: 90,
  },
  {
    name: "Proteus",
    image: "foto/Proteus.png",
    proficiency: 85,
  },
  {
    name: "QGIS",
    image: "foto/QGIS.png",
    proficiency: 95,
  },
  {
    name: "AutoCAD",
    image: "foto/AutoCAD.png",
    proficiency: 82,
  },
  {
    name: "HomerPro",
    image: "foto/HomerPro.png",
    proficiency: 75,
  },
  {
    name: "SolidWorks",
    image: "foto/pngwing.com.png",
    proficiency: 98,
  },
  {
    name: "-",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Autodesk_Logo.svg/200px-Autodesk_Logo.svg.png",
    proficiency: 70,
  },
  {
    name: "-",
    image: "https://upload.wikimedia.org/wikipedia/commons/thumb/6/60/National_Instruments_Logo.svg/200px-National_Instruments_Logo.svg.png",
    proficiency: 72,
  },
];

export const profileImage = "foto/aku.png";